import streamlit as st
import numpy as np
import re
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

# =========================
# PDF Generation Function
# =========================
def generate_pdf_report(score, risk_level, bf_time, dict_time, gpu_time, length, entropy, pattern_risk):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, "PASSWORD SECURITY REPORT")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, f"Analysis Date: {datetime.now().strftime('%d %B %Y')}")
    c.drawString(50, height - 100, f"Security Score: {score}/100")
    c.drawString(50, height - 120, f"Risk Level: {risk_level}")

    c.drawString(50, height - 150, "Estimated Crack Time:")
    c.drawString(70, height - 170, f"- Brute Force: {bf_time}")
    c.drawString(70, height - 190, f"- Dictionary Attack: {dict_time}")
    c.drawString(70, height - 210, f"- GPU Attack: {gpu_time}")

    c.drawString(50, height - 240, "Key Findings:")
    c.drawString(70, height - 260, f"- Password Length: {length} characters")
    c.drawString(70, height - 280, f"- Entropy Level: {entropy}")
    c.drawString(70, height - 300, f"- Pattern Risk: {pattern_risk}")

    c.drawString(50, height - 330, "Recommendations:")
    c.drawString(70, height - 350, "- Increase length to at least 14+ characters")
    c.drawString(70, height - 370, "- Avoid dictionary-based words")
    c.drawString(70, height - 390, "- Use mixed character sets (A-Z, a-z, 0-9, symbols)")

    c.drawString(50, height - 430, "Generated by Password Risk Intelligence Platform")
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

# =========================
# Password Analysis Function
# =========================
def analyze_password(pw):
    length = len(pw)
    score = min(length * 5, 50)
    if re.search(r"[A-Z]", pw): score += 10
    if re.search(r"[a-z]", pw): score += 10
    if re.search(r"\d", pw): score += 10
    if re.search(r"[!@#$%^&*(),.?\":{}|<>]", pw): score += 10
    score = min(score, 100)
    if score < 50: verdict = "DANGER"
    elif score < 80: verdict = "WEAK"
    else: verdict = "SECURE"

    w, b = 1.5, -5
    bf_seconds = np.exp(w*length + b)
    dict_seconds = bf_seconds / 2
    gpu_seconds = bf_seconds / 1000
    return score, verdict, bf_seconds, dict_seconds, gpu_seconds, length, "Medium", "Low"

# =========================
# Streamlit UI
# =========================
st.set_page_config(page_title="Password Fortress", page_icon="🔐", layout="wide")

# Header
st.markdown("""
<div style='background: linear-gradient(90deg, #FF6B81, #FF4C7D); padding:40px; border-radius:15px; text-align:center;'>
    <h1 style='color:white; font-size:48px;'>🔐 Password Fortress</h1>
    <p style='color:white; font-size:20px;'>
        Protect your accounts with data-driven password strength predictions.<br>
        Free version shows basic score. Premium unlocks advanced analysis. Enterprise is for teams.
    </p>
</div>
""", unsafe_allow_html=True)

# Password Input
st.subheader("🔑 Check Your Password")
password = st.text_input("Enter your password:", type="password")

if password:
    score, verdict, bf_time, dict_time, gpu_time, length, entropy, pattern_risk = analyze_password(password)
    st.subheader("Password Analysis")
    if verdict == "DANGER":
        st.error(f"{verdict} — Score: {score}/100")
    elif verdict == "WEAK":
        st.warning(f"{verdict} — Score: {score}/100")
    else:
        st.success(f"{verdict} — Score: {score}/100")
    
    st.write(f"Estimated Brute Force Crack Time: {bf_time:.2f} sec")
    st.write(f"Estimated Dictionary Crack Time: {dict_time:.2f} sec")
    st.write(f"Estimated GPU Crack Time: {gpu_time:.2f} sec")

    # PDF download
    pdf_buffer = generate_pdf_report(score, verdict, f"{bf_time:.2f} sec",
                                     f"{dict_time:.2f} sec", f"{gpu_time:.2f} sec",
                                     length, entropy, pattern_risk)
    st.download_button(
        label="📄 Download PDF Report",
        data=pdf_buffer,
        file_name=f"Password_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
        mime="application/pdf"
    )

# Subscription Plans
st.markdown("---")
st.header("💼 Choose Your Plan")
col1, col2, col3 = st.columns(3)

card_style = "padding:20px; border-radius:15px; box-shadow:2px 2px 15px rgba(0,0,0,0.1); background-color:pink; margin-bottom:20px;"

# Free Plan
with col1:
    st.markdown(f"""
    <div style='{card_style}'>
        <h3>Free Plan</h3>
        <ul>
            <li>Limited password analyses/day</li>
            <li>Basic score</li>
            <li>General strength classification</li>
        </ul>
        <p><strong>Purpose:</strong></p>
        <ul>
            <li>Attract users</li>
            <li>Build trust</li>
            <li>Encourage upgrade</li>
        </ul>
    </div>
    """, unsafe_allow_html=True)
    if st.button("Start Free", key="free_plan"):
        st.success("🎉 You are using the Free Plan!")

# Premium Plan
with col2:
    st.markdown(f"""
    <div style='{card_style}'>
        <h3>💎 Premium Plan</h3>
        <p><strong>Price:</strong> $9.99 / month or $99 / year</p>
        <ul>
            <li>Unlimited analyses</li>
            <li>Advanced risk scoring</li>
            <li>Detailed crack-time estimation</li>
            <li>Downloadable PDF reports</li>
            <li>Personalized recommendations</li>
        </ul>
        <p><strong>Revenue Model:</strong> Monthly/yearly subscription</p>
    </div>
    """, unsafe_allow_html=True)
    if st.button("Subscribe Now", key="premium_plan"):
        st.success("💳 Redirecting to subscription page...")

# Enterprise Plan
with col3:
    st.markdown(f"""
    <div style='{card_style}'>
        <h3>🏢 Enterprise Plan</h3>
        <p><strong>Price:</strong> Contact for quote</p>
        <ul>
            <li>Bulk password analysis</li>
            <li>Organizational risk overview</li>
            <li>Advanced reporting dashboard</li>
            <li>API access</li>
            <li>Custom branding options</li>
        </ul>
        <p><strong>Commercial Strategy:</strong></p>
        <ul>
            <li>Freemium drives adoption</li>
            <li>Premium monetizes individuals</li>
            <li>Enterprise generates recurring revenue</li>
        </ul>
    </div>
    """, unsafe_allow_html=True)
    if st.button("Contact Sales", key="enterprise_plan"):
        st.success("📧 Redirecting to Enterprise sales contact page...")
